### ISSUE TITLE
Support the download of all Metathesaurus files

### ISSUE THREAD

**Issue by Minitour** [cthoyt/umls_downloader#2]
https://download.nlm.nih.gov/umls/kss/2021AB/umls-2021AB-metathesaurus.zip

It is a bit different from [MRCONSO.RRF](https://download.nlm.nih.gov/umls/kss/2021AB/umls-2021AB-mrconso.zip) as there are multiple RRF files within it.

**Comment by cthoyt** [comment]
The place where the download happens is actually quite simple:

https://github.com/cthoyt/umls_downloader/blob/ac316c3cf6b5adf621bd9c9b03febc673fa535a1/src/umls_downloader/api.py#L68-L89

Would be happy to accept a PR if you want to take a shot at this

**Comment by Minitour** [comment]
I ended up simply using ` download_tgt` to download what I need without the need of having the code be within the framework itself.

**Comment by cthoyt** [comment]
I did want to give the opportunity for an open source contribution so I didn't provide this immediately for you - but it's the case that the update will take me less than 5 minutes since I already know how the code works. Either way I will add this to the library when I return from vacation.

**Comment by cthoyt** [comment]
@Minitour please see the solution provided in https://github.com/cthoyt/umls_downloader/commit/6e5be8d2b6c4c6f277e07b768ae812557ddc9fdc
